# Generated by Django 4.0.4 on 2022-05-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=200, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
