# Generated by Django 4.0.4 on 2022-05-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='short_description',
            field=models.CharField(default='default', max_length=50, verbose_name=200),
            preserve_default=False,
        ),
    ]
