# Generated by Django 4.0.4 on 2022-05-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_disease_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(default='def', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='prevention',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(max_length=2000),
        ),
    ]
