# Generated by Django 4.0.4 on 2022-05-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_disease_description_alter_disease_prevention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='display_image',
            field=models.ImageField(default='uploads/disease/default.jpg', upload_to='uploads/disease'),
            preserve_default=False,
        ),
    ]
