# Generated by Django 4.0.4 on 2022-05-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0004_disease_display_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='display_image',
            field=models.ImageField(upload_to='disease'),
        ),
    ]
