# Generated by Django 4.0.4 on 2022-05-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0006_alter_disease_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='slider_image1',
            field=models.ImageField(default='default.jpg', upload_to='disease'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='slider_image2',
            field=models.ImageField(default='default.jpg', upload_to='disease'),
            preserve_default=False,
        ),
    ]
