# Generated by Django 4.0.4 on 2022-05-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0007_disease_slider_image1_disease_slider_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
