# Generated by Django 4.0.4 on 2022-05-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diseases', '0007_disease_slider_image1_disease_slider_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('specialization_description', models.TextField(max_length=2000)),
                ('direction', models.TextField(max_length=2000)),
                ('display_image', models.ImageField(upload_to='disease')),
                ('slider_image1', models.ImageField(upload_to='disease')),
                ('slider_image2', models.ImageField(upload_to='disease')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('specialization', models.ManyToManyField(to='diseases.disease')),
            ],
        ),
    ]
