# Generated by Django 4.0.4 on 2022-05-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
